name: Merge to UAT
on:
  pull_request:
    types: [closed]
    branches:
      - systest
jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge to UAT
        run: |
          echo "Merging changes to UAT environment"
          # Add your deployment steps here
